# lovelace_gen

type: custom:layout-card
cards:
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: 'Télecommandes Salon'
    filter:
      include:
        - entity_id: "automation.telecommande*"
        - entity_id: "automation.btn*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: 'Eclairage'
    filter:
      include:
        - entity_id: "automation.eclairage*"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: 'On'
    filter:
      include:
        - entity_id: "automation.*"
          state: "on"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: 'Off'
    filter:
      include:
        - entity_id: "automation.*"
          state: "off"
  - type: custom:monster-card
    show_empty: false
    card:
      type: entities
      title: 'Notifications'
    filter:
      include:
        - entity_id: "automation.notif*"