# ---------------------------------------------------------------- #
#
# Home Assistant Configuration
# File : configuration.yaml
# 
# ---------------------------------------------------------------- #
homeassistant:
  name: Home
  customize: !include customize.yaml
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Paris
  packages: 
    zigate: !include packages/zigate.yaml 
    pkg_cellier: !include_dir_named packages/cellier/
    pkg_vacuum: !include packages/vacuum.yaml
    pkg_battery: !include_dir_named packages/battery/
    pkg_fr24: !include packages/fr24.yaml
    pkg_salon: !include packages/salon.yaml

rflink:
  port: /dev/ttyUSB1

securitas_direct:
  username: !secret securitas_direct_username
  password: !secret securitas_direct_password
  code: !secret securitas_direct_code
  country: !secret securitas_direct_country

lovelace_gen:

lovelace:
  mode: yaml

shell_command:
  dummy_secrets: grep -Ev '^#' /homeassistant/homeassistant/.homeassistant/secrets.yaml | awk -F ' ' '{print $1,$4}' > /homeassistant/homeassistant/.homeassistant/dummy_secrets.yaml

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    latitude: !secret home_latitude
    longitude: !secret home_longitude

zwave:
  usb_path: /dev/ttyACM0
  device_config: !include zwave_device_config.yaml

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

zigate:
  enable_led : false

recorder:
  purge_keep_days: 1
  purge_interval: 2
  db_url: !secret db_url
  exclude:
    domains:
      - automation
      - weblink
      - device_tracker
      - script
      - zwave

http:
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate 
  ssl_key: !secret http_ssl_key 

# Huawei_LTE 
# huawei_lte:
#   - url: !secret huawei_lte_url
#     username: !secret huawei_lte_username
#     password: !secret huawei_lte_password

frontend:
  themes: !include_dir_merge_named themes
config:
updater:  
discovery:
history:
logbook:
sun:
system_health:
wake_on_lan:
mobile_app:

# INCLUDE

person: !include configs/person.yaml
group: !include configs/groups.yaml
automation old: !include_dir_merge_list automation/
input_boolean: !include configs/input_boolean.yaml
script: !include configs/scripts.yaml
switch: !include configs/switch.yaml
remote: !include configs/remote.yaml
sensor: !include configs/sensor.yaml
google_assistant: !include configs/googleassistant.yaml
notify: !include configs/notify.yaml
logger: !include configs/logger.yaml
device_tracker: !include configs/device_tracker.yaml
timer: !include  configs/timer.yaml
