# lovelace_gen

title: Home

resources:
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  - url: !file /community_plugin/monster-card/monster-card.js
    type: js
  - url: !file /community_plugin/button-card/button-card.js
    type: module
  - url: !file /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: !file /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: !file /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: !file /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/lovelace-multiple-entity-row/multiple-entity-row.js
    type: js
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module

views:
  - title: Home
    icon: mdi:home
    panel: true
    cards:
      - !include lovelace/home.yaml
  - title: Salon
    icon: mdi:sofa
    panel: true
    cards:
      - !include lovelace/salon.yaml
  - title: VACUUM
    icon: mdi:robot-vacuum
    panel: true
    cards:
      - !include lovelace/vacuum.yaml
  - title: AUTOMATION
    icon: mdi:home-automation
    panel: true
    cards:
      - !include lovelace/automation.yaml
  - title: BATTERY
    icon: mdi:battery-50
    panel: true
    cards:
      - !include lovelace/battery.yaml

  - title: TODO
    icon: mdi:markdown
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - type: markdown
            content: >
              ## Todo 
                * Resync sonde fuite SDB
          - type: entities
            title: Admin Control
            show_header_toggle: false    
            entities:
              - entity: input_boolean.zigate_permit_join
                name: Permit Join Zigate 30s
