# lovelace_gen

title: Home

resources:
  - url: /community_plugin/lovelace-layout-card/layout-card.js
    type: js
  - url: !file /community_plugin/monster-card/monster-card.js
    type: js
  - url: !file /community_plugin/button-card/button-card.js
    type: module
  - url: !file /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: !file /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: !file /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/lovelace-card-tools/card-tools.js
    type: js
  - url: !file /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: module
  - url: /community_plugin/button-entity-row/button-entity-row.js
    type: module
  - url: /community_plugin/weather-card/weather-card.js
    type: module

views:
  - title: TAB1
    icon: mdi:home
    panel: true
    cards:
      - !include lovelace/tab1.yaml
  - title: Salon
    icon: mdi:sofa
    panel: true
    cards:
      - !include lovelace/salon.yaml
  - title: Cuisine
    icon: mdi:fridge-outline
    panel: true
    cards:
      - !include lovelace/cuisine.yaml
  - title: Jardin
    icon: mdi:flower
    panel: true
    cards:
      - !include lovelace/jardin.yaml
  - title: VACCUM
    icon: mdi:robot-vacuum
    panel: true
    cards:
      - !include lovelace/vaccum.yaml
  - title: THERMAL
    icon: mdi:thermometer-lines
    panel: true
    cards:
      - !include lovelace/thermal.yaml
  - title: AUTOMATION
    icon: mdi:home-automation
    panel: true
    cards:
      - !include lovelace/automation.yaml
  - title: BATTERY
    icon: mdi:battery-50
    panel: true
    cards:
      - !include lovelace/battery.yaml
  - title: NOTIFICATIONS
    icon: mdi:battery-50
    panel: true
    cards:
      - !include lovelace/notifications.yaml

  - title: TODO
    icon: mdi:markdown
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - type: markdown
            content: >
              ## Todo 
                * Resync sonde fuite SDB
                * Alerte porte ouverte
          - type: entities
            title: Admin Control
            show_header_toggle: false    
            entities:
              - entity: input_boolean.zigate_permit_join
                name: Permit Join Zigate 30s
