# ---------------------------------------------------------------- #
#
# Home Assistant Device Tracker configuration
# File : device_tracker.yaml
# 
# ---------------------------------------------------------------- #
  - platform: nmap_tracker
    home_interval: 10
    hosts:
      - !secret track_ip_tv
  - platform: unifi
    verify_ssl: false
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password