
# DEFAULT VIEW
  default_view:
    view: false
    icon: mdi:home
    entities:
      - weather.openweathermap
      - media_player.salon


## LIGHTS 

  lights:
    view: true
    name: Eclairage
    icon: mdi:lightbulb-on-outline
    entities:
      - group.exterieur
      - group.salon

  presence_home:
    view: true
    name: Presence Home
    icon: mdi:human-male-female
    entities:
      - person.elodie_2
      - person.mickael_2

  exterieur:
    name: Exterieur
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_2
  salon:
    name: Salon
    entities:
      - light.salon_all_lights
      - light.salon_lampe_1
      - light.salon_lampe_2
      - light.salon_lampe_3
      - light.salon_lampe_4
      - light.totem_light
