
# DEFAULT VIEW
  default_view:
    icon: mdi:home
    entities:
      - weather.openweathermap
      - media_player.salon


## LIGHTS 

  lights:
    name: Eclairage
    icon: mdi:lightbulb-on-outline
    entities:
      - group.exterieur
      - group.salon

  presence_home:
    name: Presence Home
    icon: mdi:human-male-female
    entities:
      - person.elodie_2
      - person.mickael_2

  exterieur:
    name: Exterieur
    entities:
      - light.fibaro_system_fgd212_dimmer_2_level_2
      - light.qubino_zmnhdd1_z_wave_plus_flush_dimmer_level
  salon:
    name: Salon
    entities:
      - light.zigate_ccccccfffed6a188_1
      - light.zigate_ccccccfffeda1b92_1
      - light.zigate_ccccccfffed80154_1
      - light.totem_light
      - light.ledstrip
