# ---------------------------------------------------------------- #
#
# Logger Configuration
# File : logger.yaml
# 
# ---------------------------------------------------------------- #
  default: warning
  # logs:
  #   zigate: debug
  #   custom_components.zigate: debug
  # logs:
  #   rflink: debug
  #   homeassistant.components.rflink: debug
