# ---------------------------------------------------------------- #
#
# Logger Configuration
# File : logger.yaml
# 
# ---------------------------------------------------------------- #
  default: info