# ---------------------------------------------------------------- #
#
# Notify Configuration
# File : notify.yaml
# 
# ---------------------------------------------------------------- #
  - platform: discord
    name: discord
    token: !secret discord_token
