# ---------------------------------------------------------------- #
#
# Notify Configuration
# File : notify.yaml
# 
# ---------------------------------------------------------------- #
  - platform: discord
    name: discord
    token: !secret discord_token
  - name: all_devices
    platform: group
    services:
      - service: mobile_app_mickael