# ---------------------------------------------------------------- #
#
# Remote Configuration
# File : remote.yaml
# 
# ---------------------------------------------------------------- #

- platform: xiaomi_miio
  host: !secret xiaomi_miio_host
  token: !secret xiaomi_miio_token
  commands:
    sound_bar_on_off:
      command:
        - raw:Z6VLAPIBAAB3AgAAVQYAAIkIAABPEQAAeyMAAISZAADUdQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBISEhIQEhISEBAQEBIQEBISEBASEhISEBASEhAQFhNXE1AQ==
    tv_on_off:
      command:
        - raw:Z6VTADMCAACVBgAApAgAAIMRAABxIwAAbJ0AAPR4AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAQAAAAAAAQEAAQEBAQEAAAABAAAAAAEBAQABAQEBBQJGAkYCRgJAA=
    sound_bar_vol_up:
      command:
        - raw:Z6VzABkCAABSAgAAegYAALAIAAB3EQAAWCMAAISZAADUdQEAOHYBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABFAQEBISEhIQEhISEBAQEBIQEhISEhAQEBIQEBAQEhISFhNYE1gTWBNYE1gTVxNXE1cTWBNXE1cTUB
    sound_bar_vol_down:
      command:
        - raw:Z6VnAEICAAB6BgAAsAgAAHYRAABXIwAAhJkAANR1AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0AAAAEBAQEAAQEBAAAAAAEBAQEBAQAAAAAAAAAAAQEBBQJGAkYCRgJGAkYCRgJGAkYCQA
