
# ---------------------------------------------------------------- #
#
# Scripts Configuration
# File : scripts.yaml
# 
# ---------------------------------------------------------------- #
  group_tv_on_off:
        alias: "ON OFF TV"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'tv_on_off'
                - 'sound_bar_on_off'

  sound_bar_on_off:
        alias: "ON OFF SOUND BAR"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'sound_bar_on_off'

  sound_bar_vol_up:
        alias: "SOUND BAR VOL UP"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'sound_bar_vol_up'

  sound_bar_vol_down:
        alias: "SOUND BAR VOL DOWN"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'sound_bar_vol_down'

  tv_on_off:
        alias: "ON OFF TV"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'tv_on_off'

  cycle_piscine_1h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 1
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_2h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 2
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_3h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 3
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_4h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 4
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'            
  vacuum_cuisine:
        alias: "Nettoyer Cuisine"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[22028,25937,25378,29487,1]]

  vacuum_salon:
        alias: "Nettoyer Salon"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16869,23858,22519,29408,1],[22517,23883,24117,26083,1]]

  vacuum_cellier:
        alias: "Nettoyer Cellier"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[24366,24782,25416,25882,1]]

  vacuum_couloir:
        alias: "Nettoyer Couloir"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[23380,19936,24180,23786,1]]

  vacuum_sdb:
        alias: "Nettoyer Salle de bain"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[24225,21149,26025,23949,1]]

  vacuum_toilette:
        alias: "Nettoyer Toilette"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[24231,20152,25831,21002,1]]

  vacuum_chambre:
        alias: "Nettoyer Chambre"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[20581,17145,25531,19895,1]]

  vacuum_zone_devant_porte:
        alias: "Nettoyage devant de porte"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[19074,29193,22224,29943,3]]

  vacuum_zone_salon:
        alias: "Nettoyage zone salon"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16801,24296,24151,29446,1],[24143,24312,25643,29462,1]]

  vacuum_zone_chambre:
        alias: "Nettoyage zone chambre"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[23367,19888,26317,23838,1],[20523,17133,26223,19883,1]]

  vacuum_zone_baie_vitree:
        alias: "Nettoyage zone baie vitree"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16781,23645,20431,25445,1],[16807,25402,17757,27602,1]]

  notify: 
    alias: 'Centre de Notification'
    description: "Centre de Notification" 
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: script.notify_discord
        data_template: 
          title: "{{ title }}"
          message: "{{ message }}"

  notify_discord:
    alias: 'Notification Discord'
    description: "Notification Discord"
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: notify.discord
        data_template:
          message: "**{{ title }}** : {{ message }}"
          target:  [!secret discord_target]

  notify_ha:
    alias: 'Notification Discord'
    description: "Notification Discord"
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: persistent_notification.create
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
