
# ---------------------------------------------------------------- #
#
# Scripts Configuration
# File : scripts.yaml
# 
# ---------------------------------------------------------------- #

  cycle_piscine_1h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 1
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_2h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 2
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_3h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 3
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_4h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 4
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'            
  notify: 
    alias: 'Centre de Notification'
    description: "Centre de Notification" 
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: script.notify_push_mobile
        data_template: 
          title: "{{ title }}"
          message: "{{ message }}"

  notify_push_mobile:
    alias: 'Notification Push Mobile'
    description: "Notification Push Mobile"
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: notify.mobile_app_mi_9t
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
      - service: notify.mobile_app_huawei_vns_l31
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"


  notify_system:
    alias: 'Notification Push Mobile'
    description: "Notification Push Mobile"
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: notify.mobile_app_mi_9t
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"

  notify_ha:
    alias: 'Notification HomeAssistant'
    description: "Notification HomeAssistant"
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: persistent_notification.create
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
