
# ---------------------------------------------------------------- #
#
# Scripts Configuration
# File : scripts.yaml
# 
# ---------------------------------------------------------------- #
  group_tv_on_off:
        alias: "ON OFF TV"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'tv_on_off'
                - 'sound_bar_on_off'

  sound_bar_on_off:
        alias: "ON OFF SOUND BAR"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'sound_bar_on_off'

  sound_bar_vol_up:
        alias: "SOUND BAR VOL UP"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'sound_bar_vol_up'

  sound_bar_vol_down:
        alias: "SOUND BAR VOL DOWN"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'sound_bar_vol_down'

  tv_on_off:
        alias: "ON OFF TV"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_49'
            data:
              command:
                - 'tv_on_off'

  hdmi_b1:
        alias: "HDMI_B1"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_28'
            data:
              command:
                - 'hdmi_b1'

  hdmi_b2:
        alias: "HDMI_B2"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_28'
            data:
              command:
                - 'hdmi_b2'

  hdmi_b3:
        alias: "HDMI_B3"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_28'
            data:
              command:
                - 'hdmi_b3'

  hdmi_b4:
        alias: "HDMI_B4"
        sequence:
          - service: remote.send_command
            entity_id: 'remote.xiaomi_miio_192_168_0_28'
            data:
              command:
                - 'hdmi_b4'
  cycle_piscine_1h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 1
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_2h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 2
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_3h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 3
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'
  cycle_piscine_4h:
        alias: "Cycle Piscine"
        sequence:
          - service: switch.turn_on
            entity_id: 'switch.piscine_relay'
          - delay:
              hours: 4
          - service: switch.turn_off
            entity_id: 'switch.piscine_relay'            
  notify: 
    alias: 'Centre de Notification'
    description: "Centre de Notification" 
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: script.notify_discord
        data_template: 
          title: "{{ title }}"
          message: "{{ message }}"

  notify_discord:
    alias: 'Notification Discord'
    description: "Notification Discord"
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: notify.discord
        data_template:
          message: "**{{ title }}** : {{ message }}"
          target:  [!secret discord_target]

  notify_ha:
    alias: 'Notification Discord'
    description: "Notification Discord"
    fields:
      message:
        description: 'The message content'
        example: 'Je suis un test de notification'
      title: 
        description: 'Title'
        example: 'Je suis un titre'
    sequence:
      - service: persistent_notification.create
        data_template:
          title: "{{ title }}"
          message: "{{ message }}"
