- alias: '[HOMEASSISTANT] Set theme at startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: frontend.set_theme
      data:
        name: "Google Light Theme"
    - service: shell_command.dummy_secrets