homeassistant: 
  customize:
    sensor.fr24_feeder:
      hidden: true
    sensor.fr24_feeder_aircraft_tracked:
      icon: mdi:airplane
    sensor.fr24_feeder_aircraft_uploaded:
      icon: mdi:airplane
    sensor.fr24_feeder_radar_code:
      icon: mdi:radar

binary_sensor:
  - platform: template
    sensors:
      fr24_feeder_receiver_connected:
        friendly_name: Receiver Connected
        value_template: '{{ is_state_attr("sensor.fr24_feeder", "rx_connected", "1") }}'
        device_class: connectivity
      fr24_feeder_link_connected:
        friendly_name: Link Connected
        value_template: '{{ is_state_attr("sensor.fr24_feeder", "feed_status", "connected") }}'
        device_class: connectivity

automation:
  - id: notification flightradar down
    alias: "[Notif] flightradar down"
    trigger:
      - platform: state
        entity_id: binary_sensor.fr24_feeder_link_connected
        to: 'off'
        for:
          minutes: 10
      - platform: state
        entity_id: binary_sensor.fr24_feeder_receiver_connected
        to: 'off'
        for:
          minutes: 10 
    condition: []
    action:
      - service: script.notify_system
        data:
          title: "[Alerte]"
          message: "FlightRadar est à l'arrêt"

  - id: notification flightradar up
    alias: "[Notif] flightradar up"
    trigger:
      - platform: state
        entity_id: binary_sensor.fr24_feeder_link_connected
        from: 'off'
        to: 'on'
        for:
          minutes: 10
      - platform: state
        entity_id: binary_sensor.fr24_feeder_receiver_connected
        from: 'off'
        to: 'on'
        for:
          minutes: 10 
    condition: []
    action:
      - service: script.notify_system
        data:
          title: "[Alerte]"
          message: "FlightRadar est de nouveau UP"

sensor:
  - platform: rest
    name: FR24 Feeder
    resource: !secret fr24_url
    value_template: '{{ value_json.feed_alias }}'
    method: GET
    scan_interval: 60
    json_attributes:
      - rx_connected
      - feed_status
      - d11_map_size
      - feed_num_ac_tracked
      - build_version
      - feed_alias
  - platform: template
    sensors:
      fr24_feeder_radar_code:
        friendly_name: Radar Code
        value_template: '{{ states.sensor.fr24_feeder.attributes["feed_alias"] }}'
      fr24_feeder_aircraft_tracked:
        friendly_name: Aircraft Tracked
        value_template: '{{ states.sensor.fr24_feeder.attributes["d11_map_size"] | round(0) }}'
        unit_of_measurement: 'aircrafts'
      fr24_feeder_aircraft_uploaded:
        friendly_name: Aircraft Uploaded
        value_template: '{{ states.sensor.fr24_feeder.attributes["feed_num_ac_tracked"] | round(0) }}'
        unit_of_measurement: 'aircrafts'
      fr24_feeder_version:
        friendly_name: Version
        value_template: '{{ states.sensor.fr24_feeder.attributes["build_version"] }}'
