homeassistant:
  customize:
    package.salon:
      customize: &customize
        package: 'Salon'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

input_select:
  ambiance_salon:
    name: Choisir l'ambiance du salon
    options:
      - Chaud
      - Blanc

automation:
  - id: light_salon_on
    alias: "[Eclairage] Allumage auto salon"
    trigger:
      platform: state
      entity_id: binary_sensor.zigate_00158d00032bd376_presence
      from: 'off'
      to: 'on'
    condition: 
      condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.luminosite_salon
        below: 5
      - condition: state
        entity_id: device_tracker.c0_41_f6_93_75_a9
        state: 'not_home'
    action:
      - service: light.turn_on
        data:
          entity_id:
            - group.salon
      - service: timer.start
        data:
          entity_id: timer.salon_lights_off_in 

  - id: light_salon_off
    alias: "[Eclairage] Extinction auto salon"
    trigger:
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.salon_lights_off_in
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: group.presence_home
          state: 'not_home'
        - condition: numeric_state
          entity_id: sensor.luminosite_salon
          above: 100
    action:
      - service: light.turn_off
        data:
          entity_id: group.salon

  - alias: light_salon_automation_input_select_chaud
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.ambiance_salon
        to: "Chaud"
    action:
      - service: light.turn_on
        data:
          entity_id: light.salon_all_lights
          rgb_color: [255,119,0]

  - alias: light_salon_automation_input_select_blanc
    hide_entity: False
    trigger:
      - platform: state
        entity_id: input_select.ambiance_salon
        to: "Blanc"
    action:
      - service: light.turn_on
        data:
          entity_id: light.salon_all_lights
          rgb_color: [255,255,255]