homeassistant:
  customize:
    package.vacuum:
      customize: &customize
        package: 'Vacuum'
      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vaccum_host
    token: !secret xiaomi_vaccum_token


# ========================================================================================= #
#                                                                                           #
#       INPUT BOOLEAN VACCUM                                                                #
#                                                                                           #
#                                                                                           #
#                                                                                           #
# ========================================================================================= #
input_boolean:
  room_cuisine:
    name: Pièce Cuisine
    initial: off
  room_salon:
    name: Pièce Salon
    initial: off
  room_cellier:
    name: Pièce Cellier
    initial: off
  room_couloir:
    name: Pièce Couloir
    initial: off
  room_sdb:
    name: Pièce Salle de bain
    initial: off
  room_toilette:
    name: Pièce Toilette
    initial: off
  room_chambre:
    name: Pièce Chambre
    initial: off
  room_bureau:
    name: Pièce Bureau
    initial: off
  zone_salon:
    name: Zone Salon
    initial: off
  zone_chambre:
    name: Zone Chambre
    initial: off
  zone_devant_porte:
    name: Zone Devant Porte
    initial: off
  zone_devant_baie_vitree:
    name: Zone Baie Vitrée
    initial: off

# ========================================================================================= #
#                                                                                           #
#       INPUT SELECT VACCUM                                                                 #
#                                                                                           #
#                                                                                           #
#                                                                                           #
# ========================================================================================= #
input_select:
  vacuum_room:
    name: Choisir la piece à nettoyer 
    options:
      - Choisir la piece
      - Cuisine
      - Salon
      - Cellier 
      - Chambre
      - Bureau
      - Couloir
      - Salle de bain
      - Toilette 
    initial: Choisir la piece

  vacuum_zone:
    name: Choisir la zone à nettoyer 
    options:
      - Choisir la zone
      - Zone Devant Porte
      - Zone Salon
      - Zone Chambre
      - Zone Baie Vitrée
    initial: Choisir la zone

# ========================================================================================= #
#                                                                                           #
#       SCRIPT VACCUM                                                                       #
#                                                                                           #
#                                                                                           #
#                                                                                           #
# ========================================================================================= #

script:
  vacuum_cuisine:
        alias: "Nettoyer Cuisine"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[22324,24808,25274,29608,1]]

  vacuum_salon:
        alias: "Nettoyer Salon"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16869,23858,22519,29408,1],[22517,23883,24117,26083,1]]

  vacuum_cellier:
        alias: "Nettoyer Cellier"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[24366,24782,25416,25882,1]]

  vacuum_couloir:
        alias: "Nettoyer Couloir"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[23380,19936,24180,23786,1]]

  vacuum_sdb:
        alias: "Nettoyer Salle de bain"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[24030,20860,25980,23710,1]]

  vacuum_toilette:
        alias: "Nettoyer Toilette"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[24231,20152,25831,21002,1]]

  vacuum_chambre:
        alias: "Nettoyer Chambre"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[20581,17145,25531,19895,1]]

  vacuum_zone_devant_porte:
        alias: "Nettoyage devant de porte"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[20350,28334,22700,29584,3]]

  vacuum_zone_salon:
        alias: "Nettoyage zone salon"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16801,24296,24151,29446,1],[24143,24312,25643,29462,1]]

  vacuum_zone_chambre:
        alias: "Nettoyage zone chambre"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[23367,19888,26317,23838,1],[20523,17133,26223,19883,1]]

  vacuum_zone_baie_vitree:
        alias: "Nettoyage zone baie vitree"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[16781,23645,20431,25445,1],[16807,25402,17757,27602,1]]

  vacuum_zone_bureau:
        alias: "Nettoyage Bureau"
        sequence:
          - service: vacuum.send_command
            data:
              entity_id: vacuum.xiaomi_vacuum_cleaner
              command: app_zoned_clean
              params: [[20692,20109,23242,23809,1]]

# ========================================================================================= #
#                                                                                           #
#       AUTOMATION VACCUM                                                                   #
#                                                                                           #
#                                                                                           #
#                                                                                           #
# ========================================================================================= #
automation:
  - id: stop vacuum alarme desactive
    alias: "[VACUUM] stop si alarme desactivé "
    trigger:
      platform: state
      entity_id: alarm_control_panel.securitas_360086
      to: 'disarmed'
    condition:
      - condition: state
        entity_id: 'vacuum.xiaomi_vacuum_cleaner'
        state: 'running'
    action:
      - service: vacuum.stop
        entity_id: vacuum.xiaomi_vacuum_cleaner
      - delay: 0:00:05
      - service: vacuum.return_to_base
        entity_id: vacuum.xiaomi_vacuum_cleaner

  - alias: Start Nettoyage d'une pièce

    trigger:
      - platform: state
        entity_id: input_select.vacuum_room
        from: 'Choisir la piece'
    condition:
      - condition: state
        entity_id: 'binary_sensor.zigate_00158d0002e214e0_onoff'
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.vacuum_room", "Cuisine") %}
              script.vacuum_cuisine
            {% elif is_state("input_select.vacuum_room", "Salon") %}
              script.vacuum_salon
            {% elif is_state("input_select.vacuum_room", "Cellier") %}
              script.vacuum_cellier
            {% elif is_state("input_select.vacuum_room", "Couloir") %}
              script.vacuum_couloir
            {% elif is_state("input_select.vacuum_room", "Salle de bain") %}
              script.vacuum_sdb
            {% elif is_state("input_select.vacuum_room", "Toilette") %}
              script.vacuum_toilette
            {% elif is_state("input_select.vacuum_room", "Chambre") %}
              script.vacuum_chambre
            {% elif is_state("input_select.vacuum_room", "Bureau") %}
              script.vacuum_bureau
            {% else %}
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.vacuum_room
        data_template:
          option: "Choisir la piece" 
      - service: input_boolean.turn_off
        entity_id: 
          - input_boolean.room_cuisine
          - input_boolean.room_salon
          - input_boolean.room_cellier
          - input_boolean.room_couloir
          - input_boolean.room_sdb
          - input_boolean.room_toilette
          - input_boolean.room_chambre
          - input_boolean.room_bureau


  - alias: Start Nettoyage d'une zone

    trigger:
      - platform: state
        entity_id: input_select.vacuum_zone
        from: 'Choisir la zone'
    condition:
      - condition: state
        entity_id: 'binary_sensor.zigate_00158d0002e214e0_onoff'
        state: 'on'
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state("input_select.vacuum_zone", "Zone Devant Porte") %}
              script.vacuum_zone_devant_porte
            {% elif is_state("input_select.vacuum_zone", "Zone Salon") %}
              script.vacuum_zone_salon
            {% elif is_state("input_select.vacuum_zone", "Zone Chambre") %}
              script.vacuum_zone_chambre
            {% elif is_state("input_select.vacuum_zone", "Zone Baie Vitrée") %}
              script.vacuum_zone_baie_vitree
            {% else %}
            {% endif %}
      - service: input_select.select_option
        entity_id: input_select.vacuum_zone
        data_template:
          option: "Choisir la zone" 
      - service: input_boolean.turn_off
        entity_id: 
          - input_boolean.zone_devant_porte
          - input_boolean.zone_salon
          - input_boolean.zone_chambre
          - input_boolean.zone_baie_vitree

  - alias: Start Fail Nettoyage

    trigger:
      - platform: state
        entity_id: input_select.vacuum_room
        from: 'Choisir la piece'
      - platform: state
        entity_id: input_select.vacuum_zone
        from: 'Choisir la zone'
    condition:
      - condition: state
        entity_id: 'binary_sensor.zigate_00158d0002e214e0_onoff'
        state: 'off'
    action:
      - service: input_select.select_option
        entity_id: input_select.vacuum_zone
        data_template:
          option: "Choisir la zone" 
      - service: input_select.select_option
        entity_id: input_select.vacuum_room
        data_template:
          option: "Choisir la pièce" 
      - service: script.notify
        data:
          title: "[NESTOR]"
          message: "Impossible de nettoyer la porte du cellier est fermée"

  - alias: Start Nettoyage Cuisine
    trigger:
      - platform: state
        entity_id: input_boolean.room_cuisine
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_cuisine
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_cuisine

  - alias: Start Nettoyage Salon
    trigger:
      - platform: state
        entity_id: input_boolean.room_salon
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_salon
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_salon

  - alias: Start Nettoyage Cellier
    trigger:
      - platform: state
        entity_id: input_boolean.room_cellier
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_cellier
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_cellier

  - alias: Start Nettoyage Couloir
    trigger:
      - platform: state
        entity_id: input_boolean.room_couloir
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_couloir
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_couloir

  - alias: Start Nettoyage Salle de bain
    trigger:
      - platform: state
        entity_id: input_boolean.room_sdb
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_sdb
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_sdb

  - alias: Start Nettoyage Toilette
    trigger:
      - platform: state
        entity_id: input_boolean.room_toilette
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_toilette
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_toilette

  - alias: Start Nettoyage Chambre
    trigger:
      - platform: state
        entity_id: input_boolean.room_chambre
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_chambre
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_chambre

  - alias: Start Nettoyage Bureau
    trigger:
      - platform: state
        entity_id: input_boolean.room_bureau
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_bureau
      - service: input_boolean.turn_off
        entity_id: input_boolean.room_bureau

  - alias: Start Nettoyage Zone devant porte
    trigger:
      - platform: state
        entity_id: input_boolean.zone_devant_porte
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_devant_porte
      - service: input_boolean.turn_off
        entity_id: input_boolean.zone_devant_porte

  - alias: Start Nettoyage Zone salon
    trigger:
      - platform: state
        entity_id: input_boolean.zone_salon
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_salon
      - service: input_boolean.turn_off
        entity_id: input_boolean.zone_salon

  - alias: Start Nettoyage Zone chambre
    trigger:
      - platform: state
        entity_id: input_boolean.zone_chambre
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_chambre
      - service: input_boolean.turn_off
        entity_id: input_boolean.zone_chambre

  - alias: Start Nettoyage Zone Baie Vitree
    trigger:
      - platform: state
        entity_id: input_boolean.zone_baie_vitree
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_baie_vitree
      - service: input_boolean.turn_off
        entity_id: input_boolean.zone_baie_vitree

  - id: Automation nettoyage zone baie vitree
    alias: Automation nettoyage zone baie vitree
    trigger:
      - at: '03:30:00'
        platform: time
    condition:
      condition: and
      conditions:
      - condition: time
        weekday:
          - mon
          - tue 
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_baie_vitree

  - id: Automation nettoyage zone salon
    alias: Automation nettoyage zone salon
    trigger:
      - at: '11:00:00'
        platform: time
    condition:
      condition: and
      conditions:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
      - condition: state
        entity_id: group.presence_home
        state: 'not_home'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_salon

  - id: Automation nettoyage cuisine nuits
    alias: Automation nettoyage cuisine nuits
    trigger:
      - at: '04:00:00'
        platform: time
    condition:
      condition: and
      conditions:
      - condition: time
        weekday:
          - mon
          - tue 
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - service: script.turn_on
        entity_id: script.vacuum_cuisine

  - id: Automation nettoyage devant porte nuits
    alias: Automation nettoyage devant porte nuits
    trigger:
      - at: '03:00:00'
        platform: time
    condition:
      condition: and
      conditions:
      - condition: time
        weekday:
          - mon
          - tue 
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_devant_porte

  - id: Automation nettoyage devant porte
    alias: Automation nettoyage devant porte
    trigger:
      - at: '10:30:00'
        platform: time
    condition:
      condition: and
      conditions:
      - condition: time
        weekday:
          - mon
          - tue 
          - wed
          - thu
          - fri
      - condition: state
        entity_id: group.presence_home
        state: 'not_home'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_devant_porte

  - id: Automation nettoyage zone chambre
    alias: Automation nettoyage zone chambre
    trigger:
      - at: '14:00:00'
        platform: time
    condition:
      condition: and
      conditions:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
      - condition: state
        entity_id: group.presence_home
        state: 'not_home'
    action:
      - service: script.turn_on
        entity_id: script.vacuum_zone_chambre

  - id: Notification Vidage aspirateur
    alias: "[Notif] Vidage aspirateur"
    trigger:
      - platform: time
        at: '20:00:00'
    condition:
      - condition: time
        weekday:
          - mon
          - wed
          - fri
    action:
      - service: script.notify
        data:
          title: "[NESTOR]"
          message: "Vider l'aspirateur"
