name: Config check
on: [push]
jobs:
  config-check-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: mv dummy_secrets.yaml secrets.yaml && touch zwave_device_config.yaml certificat.pem key.pem
      - uses: kpucynski/action-ha-config-check@master
        with:
          ha_version: "latest"
        env:
          HASS_EXTRA_ARGS: "-f -s -i"
